name: type blog
markdown: redcarpet
highlighter: pygments
excerpt_separator: <!--break-->
gems:
  - jekyll-sitemap
author:
  name: 'Charlie Marsh'
  email: 'charlie.r.marsh@gmail.com'
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - README.md
  - yarn.lock
