name: type blog
markdown: redcarpet
highlighter: pygments
excerpt_separator: <!--break-->
gems:
  - jekyll-sitemap
author:
  name: 'Charlie Marsh'
  email: 'charlie@khanacademy.org'
exclude:
  - node_modules
  - package.json
  - README.md
  - yarn.lock
