application: crmarsh416
version: 1
api_version: 1
runtime: python27
threadsafe: true

handlers:
- url: /css
  static_dir: css
  mime_type: text/css
- url: /js
  static_dir: js
  mime_type: text/javascript
- url: /img
  static_dir: img
  mime_type: image/png
- url: /pdf
  static_dir: pdf
  mime_type: application/pdf
